### ISSUE TITLE
Select ors are not used

### ISSUE THREAD

**Issue by pfgithub** [ShiftOS/Project-Orion#2]
Knowledge input and shiftorium should be put together in one case until they are implemented and can be separated

https://github.com/ShiftOS/Project-Orion/blob/master/ShiftOS/ShiftOS/Terminal.vb#L135-L138

**Comment by rezedus** [comment]
I don't really think it matters in this case. The separate entries also act as a placeholder.

**Comment by NarodGaming** [comment]
I really don't see how this is an issue.
