### ISSUE TITLE
Don't abuse #Region

### ISSUE THREAD

**Issue by rezedus** [ShiftOS/Project-Orion#4]
https://github.com/ShiftOS/Project-Orion/blob/master/ShiftOS/ShiftOS/Terminal.vb

Regions are for tying together related stuff in larger files, an example would be methods implemented by implementing an interface or windowing code in original ShiftOS applications. For explaining the purpose of single methods use [XML comments](https://msdn.microsoft.com/en-us/magazine/dd722812.aspx), those are then going to appear in intellisense. For explaning parts of code use regular comments.

**Comment by NarodGaming** [comment]
Yeah, all the 'command' regions should be put into one... I might change around some of the regions soon.

**Comment by RandomMelon** [comment]
I fixed this in my latest commit, closed.
